#!/bin/bash

echo "=================================================="
echo "  PRODUCTION SECRETS SETUP GUIDE"
echo "=================================================="
echo ""
echo "Run these commands ONE AT A TIME:"
echo ""
echo "1. STRIPE (Payment Processing)"
echo "   npx wrangler pages secret put STRIPE_SECRET_KEY --project-name webapp"
echo "   npx wrangler pages secret put STRIPE_PUBLISHABLE_KEY --project-name webapp"
echo ""
echo "2. JWT (Authentication)"
echo "   npx wrangler pages secret put JWT_SECRET --project-name webapp"
echo ""
echo "3. RESEND (Email Notifications)"
echo "   npx wrangler pages secret put RESEND_API_KEY --project-name webapp"
echo "   npx wrangler pages secret put FROM_EMAIL --project-name webapp"
echo ""
echo "4. TWILIO (SMS Notifications)"
echo "   npx wrangler pages secret put TWILIO_ACCOUNT_SID --project-name webapp"
echo "   npx wrangler pages secret put TWILIO_AUTH_TOKEN --project-name webapp"
echo "   npx wrangler pages secret put TWILIO_PHONE_NUMBER --project-name webapp"
echo ""
echo "=================================================="
echo ""
echo "Each command will prompt you to enter the secret value."
echo "Press Enter after pasting each value."
echo ""
